# Enable blockchain
blockchain:
  eth:
    # enable | disable ethereum collector
    enabled: true

# Kafka common
kafka:
  common:
    bootstrap:
      servers: 192.168.79.128:9092
  eth:
    topic:
      # ethereum block event message topic
      block: eth-block
      # ethereum tx event message topic
      tx: eth-tx
      # ethereum pending tx event message topic
      pendingTx: eth-pending-tx

# Blockchain node infos
nodes:
  eth:
    networks:
      - networkName: Private
        blockTime: 15000
        pendingTxPollingInterval: 1000
        nodes:
          - nodeName: Node01
            httpUrl: http://192.168.79.128:8540/
            ipcPath:
            webSocketUrl:
          #- nodeName: Node02
           # httpUrl:
            #ipcPath:
            #webSocketUrl: ws://192.168.79.128:8451

# logging
logging:
  config: classpath:logback.xml

# Server
server:
  port: 8080
