#######################################################
# Blockchain configuration
#######################################################
blockchain:
  eth:
    # enable | disable ethereum collector
    enabled: true

#######################################################
# Blockchain node configuration
#######################################################
nodes:
  eth:
    networks:
      - networkName: Private
        blockTime: 15000
        pendingTxPollingInterval: 1000
        nodes:
          - nodeName: Node01
            httpUrl: http://192.168.79.129:8450
            ipcPath:
            webSocketUrl:
          - nodeName: Node02
            httpUrl:
            ipcPath:
            webSocketUrl: ws://192.168.79.128:8451

#######################################################
# Kafka configuration
#######################################################
kafka:
  enabled: false
  common:
    bootstrap:
      servers: 192.168.79.128:9092
  # produce ethereum messages
  eth:
    enabled: false
    topic:
      # ethereum block event message topic
      block: eth-block
      # ethereum tx event message topic
      tx: eth-tx
      # ethereum pending tx event message topic
      pendingTx: eth-pending-tx

#######################################################
# Elasticsearch configuration
#######################################################
elasticsearch:
  enabled: true
  common:
    hosts:
      - 192.168.5.78:9200
    # timeout seconds
    connectTimeout: 5
    socketTimeout: 3
  # saving ethereum data to elasticsearch
  eth:
    enabled: true
    # rolling index rule {networkName}-{blocks | transactions}-{startBlockNumber}
    # such as ["network-blocks-0", "network-blocks-100000"] indices
    # => blocks with number range [0,100000) are stored in "network-blocks-0" index
    # => blocks with number range [100000,200000) are stored in "network-blocks-100000" index
    # => transaction is also applied depend on block number
    rollingRule: true
    rollingBlockNumber: 100000
    rollingTxNumber: 50000

#######################################################
# logging
#######################################################
logging:
  config: classpath:logback.xml

#######################################################
# Server & Spring
#######################################################
server:
  port: 8080
